name: Push To Docker Registry
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v1

      - name: Install clang
        run: sudo apt-get update && sudo apt-get install clang

      - name: Compile tests
        run: cmake -DCMAKE_CXX_COMPILER=clang++ . && cmake --target gtest-run

      - name: List dirs now
        run: ls

      - name: Run tests
        run: cd bin && ./gtest_run

  publish_docker:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Publish to Docker Registry
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

        run: |
          echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin
          docker image build -t supercmmetry/hybridzip:latest -f ./ops/images/cpp.Dockerfile .
          docker push supercmmetry/hybridzip:latest

